# Generated by Django 3.1.2 on 2020-10-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_tybe',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
