# Generated by Django 3.1.2 on 2020-10-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_tybe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_tybe',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15),
        ),
    ]
